services:
  ztnet:
    build: .
    image: ztnet:sqlite-single
    container_name: ztnet
    working_dir: /app
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ztnet-data:/app/data
      - zerotier:/var/lib/zerotier-one
    ports:
      - 3000:3000
      - "9993:9993/udp"
    environment:
      DATABASE_URL: "file:/app/data/ztnet.sqlite"
      SQLITE_DIR: "/app/data"
      ZT_ADDR: "http://127.0.0.1:9993"
      ZT_SECRET_FILE: "/var/lib/zerotier-one/authtoken.secret"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "random_secret"

volumes:
  ztnet-data:
  zerotier:
